version: '3.9'

services:

  mongo:
    image: mongo:latest
    container_name: auth-mongo

    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
      MONGO_INITDB_DATABASE: user
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    volumes:
      - mongodata:/data/db
    restart: always
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null

volumes:
  mongodata:

